name: AutoDeploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - LICENSE
      - README.md

jobs:
  build-and-deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: Node环境
        uses: actions/setup-node@v2
        with:
          node-version: 22.9.0

      - uses: pnpm/action-setup@v2
        name: 安装pnpm
        with:
          version: 9.12.1
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: 缓存pnpm依赖
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: 安装依赖
        if: steps.cache-hit.outputs.cache-hit != 'true'
        run: pnpm install

      - name: 打包构建
        run: pnpm run build

      - name: 部署到Page分支
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true  # 保持page分支历史干净